### ISSUE TITLE
Nota Nuninvest

### ISSUE THREAD

**Issue by alexsilva** [thiagosalvatore/correpy#1]
Achei muito interessante esse projeto, porém tive problema no parser de uma nota da NuInvest (nubank).
![image](https://user-images.githubusercontent.com/2024086/220419286-398db854-0837-4df4-8ccb-e5695e56cee8.png)
###
O problema é que uma lista vazia é retornada porque "C.I" não existe.

**Comment by alexsilva** [comment]
Consegui criar um parser funcional, semelhante ao padrão, que consegue extrair os dados dessa nota
[nuinvest parser](https://github.com/alexsilva/correpy/blob/main/correpy/parsers/brokerage_notes/b3_parser/nuinvest.py)

**Comment by vicentenetoPE** [comment]
esse é o padrão sinacor?

**Comment by alexsilva** [comment]
> esse é o padrão sinacor?

Não tenho certeza do padrão de nota da nuinvest mas usei a mesma lógica (com alguns ajustes), para extrair os dados.

Já testei sobre sobre várias notas que tenho.

**Comment by thiagosalvatore** [comment]
A NuInvest te oferece a nota em 2 formatos (esse que voce mandou e o padrao sinacor). Esse parser em específico só funciona com notas no padrão Sinacor, por isso deve ter dado problema

**Comment by thiagosalvatore** [comment]
@alexsilva fica a vontade pra abrir um PR com esse parser pra dentro do projeto. Demorei pra responder porque o github por algum motivo nao esta me notificando
