### ISSUE TITLE
Uso do parser correto dependendo das notas (B3 ou Nuinvest)

### ISSUE THREAD

**Issue by rduran** [thiagosalvatore/correpy#11]
Olá Thiago, estou testando a API (excelente trabalho, btw!) e queria saber se há como identificar "on the fly" o tipo de nota que está sendo parseada. As da Clear funcionam perfeito com o exemplo base, mas as da NuInvest não. Vou adicionar as do BTG também nos testes e te falo depois. Tem como fazer esse filtro pelo arquivo? 

Gratidão

**Comment by thiagosalvatore** [comment]
Fala @rduran, tudo bem? 

Uma possibilidade seria a gente ir na tentativa e erro (criar algo aqui dentro que tenta com 1, depois tenta com outra, etc). 

As da nuinvest só funcionam no parser default se voce baixar elas no padrão sinacor. Caso contrário precisa usar o parser específico da nuinvest mesmo.

Pra detectar a corretora automaticamente daria pra tentar buscar por um texto específico no PDF também, mas nunca tentei (pode ser que funcione bem) - vou tentar explorar e ver se funciona

**Comment by rafaael1** [comment]
Olá @thiagosalvatore, tranquilo?

Essa adição deixará o parser "inteligente", e com compatibilidade a outras notas que ainda não funcionam perfeitamente.

Acho que uma possibilidade seria identificar pelo CNPJ da corretora, já que é uma informação fidedigna e dificilmente muda. A partir dessa informação, o parser especifico pode então ser aplicado.

**Comment by thiagosalvatore** [comment]
@rafaael1 @rduran eu não tenho nota da NuInvest, então nao consigo testar.

https://github.com/thiagosalvatore/correpy/pull/19

Esse PR adiciona a funcionalidade que vcs falaram. Algum de vcs consegue testar com uma nota da nuinvest pra ver se ele identifica o parser corretamente? Pode ser que o CNPJ que eu usei esteja errado
