### ISSUE TITLE
Identificação do tipo do ativo

### ISSUE THREAD

**Issue by rafaael1** [thiagosalvatore/correpy#14]
@thiagosalvatore, @alexsilva tudo bem?

Sabem se teria como fazer a identificação do tipo para cada ativo na nota?

Tipos: Ações, FII's, BDR's e outros títulos.

Penso em facilitar a gestão dos investimentos.

**Comment by thiagosalvatore** [comment]
Exato, boa parte das corretoras só tem o nome do ativo e aí nesse caso a forma que eu acabo fazendo em projetos pessoais é tentar ter todos os ativos que existem na bolsa em um banco pessoal e buscar o nome lá

**Comment by thiagosalvatore** [comment]
Vou fechar essa issue porque nao temos como resolver isso com a lib, pelo menos não hoje em dia.
