### ISSUE TITLE
Quantidades importadas erradas

### ISSUE THREAD

**Issue by pinhorc** [thiagosalvatore/correpy#16]
Alguém já teve problema com quantidades acima de 1.000 ações vindo zeradas? Isso parece ocorrer porque nas notas que estou tentando importar vem "1.000" ao invés de "1000" e pelo ponto estar ali o parser entende não ser do formato "Decimal" e importar como zero.

**Comment by pinhorc** [comment]
Eu vi que em utils.py tem o bloco abaixo, que deveria cuidar do problema acima, mas por algum motivo, não está funcionando!

[def extract_value_from_line(*, line: str) -> Decimal:
    if total_value := re.findall(NUMBER_STRUCTURE_REGEX, line):
        return Decimal(total_value[-1].replace(".", "").replace(",", "."))

    return Decimal(0)](url)

**Comment by thiagosalvatore** [comment]
a sua nota está no formato sinacor ou é no formato específico de alguma corretora?

**Comment by pinhorc** [comment]
Oi Thiago. É a nota "Padrao SINACOR" da XP.
Att
Rafael Pinho

**Comment by alexandretperez** [comment]
Olá @pinhorc e @thiagosalvatore , tive o mesmo problema.
A expressão regular não encontra valores como 1000 ou 1.000 ou 15.000, etc.

Incluí a expressão `\d+\.?\d{3}(?!,)` para estes casos, a versão atualizada do NUMBER_STRUCTURE_REGEX ficou assim:

`(?<![\d(\.|,)])(?:0,\d{2}|\d+\.?\d{3}(?!,)|[1-9]\d{0,2}(?:\.\d{3})*,\d{2}|[1-9]\d{0,2})(?![\d(\.|,)])`

**Comment by pinhorc** [comment]
Então assim funcionou? Maravilha! Obrigado irei testar por aqui!
Rafael Pinho

**Comment by thiagosalvatore** [comment]
boa. @alexandretperez quer abrir um PR com a correção?

**Comment by alexandretperez** [comment]
@thiagosalvatore, abro sim, durante esta semana!

**Comment by thiagosalvatore** [comment]
Correção mergeada na versao 0.4.1
