### ISSUE TITLE
AttributeError: 'ParserFactory' object has no attribute 'parse_brokerage_note'

### ISSUE THREAD

**Issue by juliahno** [thiagosalvatore/correpy#23]
Boa tarde, Thiago. 

Estou tentando importar uma nota de corretagem (PDF) da Toro (padrão SINACOR), mas estou recebendo o erro abaixo. Você pode analisar, por favor?
 
![Screenshot 2024-07-06 at 17 32 09](https://github.com/thiagosalvatore/correpy/assets/43688750/187fcbad-9d1e-4306-8ef4-4b1d4e645b33)

![Screenshot 2024-07-06 at 17 33 27](https://github.com/thiagosalvatore/correpy/assets/43688750/cf443838-0c68-4979-88e0-c1cba8f7d326)

``` 
import io

from correpy.parsers.brokerage_notes.parser_factory import ParserFactory

with open('Toro0607.pdf', 'rb') as f:
    content = io.BytesIO(f.read())
    content.seek(0)
    
    brokerage_notes = ParserFactory(brokerage_note=content, password="password").parse_brokerage_note()
```

`AttributeError: 'ParserFactory' object has no attribute 'parse_brokerage_note'`

**Comment by trunet** [comment]
usa `.parse()`

**Comment by thiagosalvatore** [comment]
A documentação estava desatualizada. Acabei de mergear um PR corrigindo isso. Obrigado por avisar.
