### ISSUE TITLE
Erro no parse do preço quando valor ultrapassa 1K

### ISSUE THREAD

**Issue by rafaael1** [thiagosalvatore/correpy#5]
O problema está relacionado quando tentamos parsear com ativos com um preço unitário igual ou acima de 1K.

Para exemplificar, pegando o preço atual de um FII's dessa lista, por exemplo o PNDL11:
[![image](https://github.com/thiagosalvatore/correpy/assets/38012343/0265a03c-118c-4d1a-b9fe-142e4216a96c)](https://www.fundsexplorer.com.br/ranking)

##### PNDL11 
- R$ 1.300,00

```
unit_value_string = "1.300,00"
unit_value_string = unit_value_string.replace(",", ".")
return Decimal(unit_value_string) 
# decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```
.

**Comment by rafaael1** [comment]
Isso ocorre porque no método `__parse_transaction_unit_price` realizamos apenas a troca da `,` pelo `.` e para valores maiores ou igual a 1K não é suficiente. O que causa o erro `decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]`, pois a string não está formatada corretamente.

**Comment by rafaael1** [comment]
Como sugestão, poderia importar o `extract_value_from_line` de utils e chamar no `__parse_transaction_unit_price` e `__parse_transaction_amount`, parseando tudo como Decimal. Vou lançar um PR com essa sugetão.

**Comment by thiagosalvatore** [comment]
Fala @rafaael1! boa! Acho que eu não tinha lidado com esse cenário realmente. Fica a vontade pra me marcar assim que abrir o PR e eu aprovo por aqui! Vou voltar a contribuir mais ativamente. Tava passando por uns problemas e por isso a demora
