### ISSUE TITLE
incorreto imposto retido na fonte

### ISSUE THREAD

**Issue by rafaael1** [thiagosalvatore/correpy#7]
Hey, @thiagosalvatore 
Essa `source_withheld_taxes` acredito que deveria ser zero no caso de operações com lucro.

Veja que:
> A alíquota do Imposto de Renda retido na fonte (dedo-duro) para operações Day Trade é de 1% sobre o lucro apurado e para as demais operações é de 0,005% sobre o valor bruto das vendas.

e
> No calculo do IRRF “dedo duro” sobre swing trade, a corretora não considera as despesas da operação, incidindo 0,005% sobre valor bruto da venda. Nas operações na Bolsa, a alíquota de 0,005% é retida se o valor do IR atingir, no mínimo, R$1,00.

Fonte original: https://www.bussoladoinvestidor.com.br/ir-em-day-trade/

### comportamento esperado
`source_withheld_taxes=Decimal('0')`

### prints

![image](https://github.com/thiagosalvatore/correpy/assets/38012343/284eccc7-cdab-48da-b5f9-7d54b8e0ab5b)

![image](https://github.com/thiagosalvatore/correpy/assets/38012343/82b8fc57-1f1d-465d-bf38-901815419441)

**Comment by thiagosalvatore** [comment]
@rafaael1 acredito que possa realmente estar errado na parte de day trade, fiz poucos testes pra esse tipo de operação. Deixa eu dar uma olhada aqui

**Comment by alexsilva** [comment]
@thiagosalvatore Pelo que andei pesquisando no campo "Observação" tem que ter um "D" para indicar day trade. Contudo nem todas as corretoras colocam essa observação.

**Comment by thiagosalvatore** [comment]
Daria pra fazer a identificação buscando um par compra<>venda do mesmo título na nota. Se tiver é day trade, mas aí a gente precisaria varrer todas as transações pra buscar os pares. Vou tentar ver se consigo fazer isso essa semana

**Comment by brunopaulon** [comment]
@thiagosalvatore vc preferiu retirar do BrokerageNote o valor de irrf declarado como retido na nota para calculator o valor por transaction, é isso? Caso positivo, não seria melhor trazer o valor de irrf da nota também como referência? Para mim o calculo manual pode  não coincidir com o calculo das corretoras, dado arredondamentos e interpretações do cálculo de lucro. Não fui  exaustivo mas a apuração da Rico nunca bate 100% com a minha, e façade a correção para a DARF. Faz sentido colocar?

Sobre o DayTrade, não sei se o cálculo é tão simples, pensando que podem haver multiplas ordens de compra e venda e algumas Sao eleitas daytrade e outras não, algumas transações podem ser parcialmente daytrade, entre outras complexidades…

**Comment by thiagosalvatore** [comment]
@brunopaulon na verdade eu decidi não usar o da nota porque pra calcular o preço médio da ação eu precisava incluir também o IRRF que foi retido na venda daquele ativo (apesar do IRRF ser pouco ele impacta o preço médio). Daria pra tentar pegar o valor da nota e aí ponderar isso por operação também

**Comment by brunopaulon** [comment]
Perfeito Thiago, e parabéns pelo projeto, está excelente. Não sou Python de carteirinha, mas achei bastante estruturado e bem organizado.

Sobre sua decisão de não incluir o irrf da nota, eu sugiro passar a incluir e deixar para o usuário decidir. O racional vem dos casos de uso: você pode usar o programa para algo mais inteligente, calculando preço médio e lucratividade, trazendo inteligência, daí você pode fazer o calculo mesmo. Ou você pode usá-lo como uma ferramenta de leitura das notas, precisando extrair com confiabilidade exatamente o que está escrito nos pdfs, que é o meu caso de uso, e daí faz sentido puxar o irrf.

Espero ter contribuído, abs

**Comment by rafaael1** [comment]
@thiagosalvatore, concordo com a sugestão do @brunopaulon, de incluir o IRRF da nota e deixar para o usuário decidir. Acho interessante ter o cálculo do preço médio, pelo menos é como pretendo usar o projeto. Inclusive estava trabalhando em alguma forma de realizar o rateio das taxas por operação/ativo.
Com relação ao cálculo do IRRF, acredito que buscando um par compra<>venda do mesmo título na nota é a melhor forma mesmo, muito bom Thiago.

Deixo também meus parabéns pelo projeto, bem organizado e está ficando excelente. abs

**Comment by alexsilva** [comment]
@rafaael1 Eu cheguei a fazer uma cálculo do [rateio de taxas](https://github.com/alexsilva/b3irpf/blob/1bbc450d302b65a61b28965991b587b3e1a4598f/irpf/plugins.py#L390). É cálculo simples que usa total das taxas dividido proporcionalmente ao total de cada compra e/ou venda.

**Comment by thiagosalvatore** [comment]
fala pessoal, obrigado demais pelas idéias! 

Vou dar uma explorada hoje nisso e ver se consigo incluir o IRRF do PDF do jeito que ele para permitir as pessoas usarem isso de outra forma também.

Com relação ao day trade em si, é um pouquinho mais complexo mas acho que da pra resolver. A maior dificuldade como o @brunopaulon levantou é que as corretoras fazem do jeito delas a divisão entre day-trade e swing-trade no mesmo dia, então é dificil saber qual daquelas operações eles incluiram como day trade ou não (se tiver swing-trade e day-trade do mesmo ativo no mesmo dia).

**Comment by thiagosalvatore** [comment]
@rafaael1 @brunopaulon estou subindo agora uma versao extraindo o IRRF da nota.

https://github.com/thiagosalvatore/correpy/pull/10

Eu testei com minhas notas da B3 no padrao Sinacor e funcionou. Deem uma olhada com as notas de voces.

**Comment by thiagosalvatore** [comment]
Fixed by #10
